<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_(4)Babyhug</name>
   <tag></tag>
   <elementGuidId>59543d6e-fea6-4819-a8f0-5909a62ff28c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.nav-pills.nav-stacked > li:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b93b057c-6e57-4ce8-96f6-3136c974990b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/brand_products/Babyhug</value>
      <webElementGuid>4470268d-baa6-472a-bb1a-3252b7069f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (4)Babyhug</value>
      <webElementGuid>4b818256-a3bd-4dad-84d0-00e4b390edcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3&quot;]/div[@class=&quot;left-sidebar&quot;]/div[@class=&quot;brands_products&quot;]/div[@class=&quot;brands-name&quot;]/ul[@class=&quot;nav nav-pills nav-stacked&quot;]/li[5]/a[1]</value>
      <webElementGuid>0e4482a3-c153-4e27-893e-d0264e01e1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[1]/following::a[1]</value>
      <webElementGuid>1a6f37be-766c-476d-a1e5-50659f9282ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Babyhug']/parent::*</value>
      <webElementGuid>e0c15016-5606-4f21-a73f-c4a82805a9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/brand_products/Babyhug')]</value>
      <webElementGuid>da162dbf-ff9a-4ecf-a6c7-8ea51d0064c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/ul/li[5]/a</value>
      <webElementGuid>b0c31e89-c13a-439e-a03e-41d8d42d11b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/brand_products/Babyhug' and (text() = ' (4)Babyhug' or . = ' (4)Babyhug')]</value>
      <webElementGuid>4b5911c7-0590-42db-b012-d94b3757df4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
