<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dress</name>
   <tag></tag>
   <elementGuidId>f636217f-d6da-4883-a397-cf5f6445dd68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Women']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.panel-body > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8024a5d4-7541-4f5c-9a5b-009e6adfbf5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category_products/1</value>
      <webElementGuid>0fd12da3-f185-48d4-bf75-d7a8c6a37f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dress </value>
      <webElementGuid>536442ab-127f-49f5-af48-345ae88351e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Women&quot;)/div[@class=&quot;panel-body&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>5e95f4b2-cd7d-4b7b-8f48-cd404f9da835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Women']/div/ul/li/a</value>
      <webElementGuid>74f72b80-6512-4fab-9398-71b01b6e13ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dress')]</value>
      <webElementGuid>23cf1733-c009-4e71-b6ee-aa1087ec6993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::a[2]</value>
      <webElementGuid>e0453be6-64c2-44c8-aaf4-de2bedcf0f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[1]/preceding::a[1]</value>
      <webElementGuid>b860c4a7-9b84-4e7b-83e7-c06e7735e37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saree'])[1]/preceding::a[2]</value>
      <webElementGuid>85045fd9-a729-4ccc-bce3-12e7c56ecb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dress']/parent::*</value>
      <webElementGuid>5e1989d9-2638-4644-940f-124080fc8b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/category_products/1')]</value>
      <webElementGuid>69ccb9a5-dead-47cd-817a-498369d8aa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/ul/li/a</value>
      <webElementGuid>3d7a3d8f-7d40-4030-85fa-85e5c1f06f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/category_products/1' and (text() = 'Dress ' or . = 'Dress ')]</value>
      <webElementGuid>9bcc330d-0c89-4c42-8919-26a3c341b42a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
