<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dress</name>
   <tag></tag>
   <elementGuidId>c2139073-a3a5-42f0-9c4c-c356d4aab80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kids > div.panel-body > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Kids']/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b5a35d7-a03d-4512-83d5-c5def0f8f28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category_products/4</value>
      <webElementGuid>88d00e31-7ced-4f39-89ce-cf8d37fbcaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dress </value>
      <webElementGuid>c4ccce4e-1212-4f4b-accc-2a8c929cd542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kids&quot;)/div[@class=&quot;panel-body&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>aaa18c33-05a9-453d-bf74-ae5228dc1d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Kids']/div/ul/li/a</value>
      <webElementGuid>eb942da8-56f4-40c1-8c38-348073a9159a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dress')])[2]</value>
      <webElementGuid>dfa99e48-5a91-4ff4-83a9-a89f1eecc0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/following::a[2]</value>
      <webElementGuid>2547b066-a67b-4994-ae99-4bc1b5ace521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops &amp; Shirts'])[1]/preceding::a[1]</value>
      <webElementGuid>93160c00-057e-4901-9b0d-f8e844e0211a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands'])[1]/preceding::a[2]</value>
      <webElementGuid>e120b58c-e58a-4c7f-a9b8-937cfcf7d4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/category_products/4')]</value>
      <webElementGuid>f7aab350-be0a-4956-a1a1-bf56078e20e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/ul/li/a</value>
      <webElementGuid>1310777d-8cba-4178-a1cc-a111a83a1b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/category_products/4' and (text() = 'Dress ' or . = 'Dress ')]</value>
      <webElementGuid>4538be64-2228-469e-b2bf-8e8d193cc308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
