<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tshirts</name>
   <tag></tag>
   <elementGuidId>45291402-0163-4acb-bc6d-d1cd8f478d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Men > div.panel-body > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Men']/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96c5ca79-a72c-4c2f-be29-4b1ba422170f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category_products/3</value>
      <webElementGuid>a2a39e65-c5b3-4859-b95d-47dad0833e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tshirts </value>
      <webElementGuid>cdfb3086-6a7d-446f-a79e-4dbb025e61fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Men&quot;)/div[@class=&quot;panel-body&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>a66a7acb-aa5f-458f-bb55-a4ea95885c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Men']/div/ul/li/a</value>
      <webElementGuid>7067fb48-ea8b-4405-ac0a-533e6b9e4621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tshirts')]</value>
      <webElementGuid>c7de4df3-2545-4c2b-8699-c30dfe89ff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saree'])[1]/following::a[2]</value>
      <webElementGuid>1931b499-175e-47d9-a2b2-445c512e8af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/preceding::a[1]</value>
      <webElementGuid>1c7078d7-4c88-4120-a800-2d06994c7fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tshirts']/parent::*</value>
      <webElementGuid>134183f2-6657-4e88-80b0-a503af541b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/category_products/3')]</value>
      <webElementGuid>beb2b057-f1c5-4fdc-bd97-a6b84767ff6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li/a</value>
      <webElementGuid>48ff49b3-800b-4d8e-876a-94035b675007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/category_products/3' and (text() = 'Tshirts ' or . = 'Tshirts ')]</value>
      <webElementGuid>2efdd2d4-d3ea-4488-a7a0-c05af1ddf567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
